version: "3.8"
name: family-kitchen-api
services:
  family-kitchen:
    container_name: family-kitchen
    build: .
    ports:
      - "5004:5004"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5004
      - MONGO_URI=mongodb://admin:password@mongodb:27017/family_kitchen?authSource=admin
      - JWT_SECRET=e77ae4c6c1c64969819ea23a5858e5a9
      - JWT_EXPIRE=30d
    networks:
      - mongo_mongo-network

networks:
  mongo_mongo-network:
    external: true





